name: Node.js CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    env:
      MONGODB_URI: mongodb://localhost:27017/test_db
      JWT_SECRET: test_secret
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      # Client setup and tests
      - name: Install Client Dependencies
        run: cd code/client && npm install
      
      - name: Run Client Tests
        run: cd code/client && npm test
        env:
          CI: true

      # Server setup and tests
      - name: Install Server Dependencies
        run: cd code/server && npm install
      
      - name: Run Server Tests
        run: cd code/server && npm test
        env:
          CI: true
          MONGODB_URI: ${{ env.MONGODB_URI }}
          JWT_SECRET: ${{ env.JWT_SECRET }}

      # Add build step if needed for deployment
      - name: Build Client
        run: cd code/client && npm run build
        env:
          CI: true