name: Node.js CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JWT_SECRET: test_secret
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      # Client setup and tests
      - name: Install Client Dependencies
        run: cd code/client && npm install
        timeout-minutes: 5
      
      - name: Run Client Tests
        run: cd code/client && npm test
        env:
          CI: true
        timeout-minutes: 5

      # Server setup and tests
      - name: Install Server Dependencies
        run: cd code/server && npm install
        timeout-minutes: 5
      
      - name: Run Server Tests
        run: cd code/server && npm test
        env:
          CI: true
          JWT_SECRET: ${{ env.JWT_SECRET }}
          NODE_ENV: ${{ env.NODE_ENV }}
          # Using mongodb-memory-server, so no need for MONGODB_URI
        timeout-minutes: 10

      # Add build step if needed for deployment
      - name: Build Client
        run: cd code/client && npm run build
        env:
          CI: true
        timeout-minutes: 5